/**
 * Space Drift - Playable Ships Specification
 */

export const SHIPS = [
  {
    id: 'drift',
    name: 'DRIFT-01',
    tag: 'Penjelajah seimbang — serba bisa di segala situasi',
    vr: 0,
    spriteKey: 'drift',
    hull: ['#e8fbff', '#8fb8d8', '#26415f'],
    acc: '#5eeaff',
    hp: 3,
    lat: 340,
    climb: 1.0,
    thrust: 1.0,
    boostCost: 35,
    radRes: 1,
    gravRes: 1,
    spd: 3,
    shd: 3,
    ctl: 3,
    bst: 3,
    perk: 'Seimbang di semua aspek — pilihan aman untuk pemula.'
  },
  {
    id: 'nova',
    name: 'NOVA-X',
    tag: 'Pemburu kecepatan — melesat cepat tapi rapuh',
    vr: 1,
    spriteKey: 'nova',
    hull: ['#fff3d8', '#ffb454', '#5c3a14'],
    acc: '#ffb454',
    hp: 2,
    lat: 330,
    climb: 1.3,
    thrust: 1.2,
    boostCost: 30,
    radRes: 1,
    gravRes: 1,
    spd: 5,
    shd: 2,
    ctl: 3,
    bst: 4,
    perk: 'Naik +30% lebih cepat · dorongan +20% · boost hanya 30 energi — tapi cuma 2 perisai.'
  },
  {
    id: 'aegis',
    name: 'AEGIS-7',
    tag: 'Benteng baja — tahan radiasi & gravitasi lubang hitam',
    vr: 2,
    spriteKey: 'aegis',
    hull: ['#e2fff0', '#7ddfa8', '#1c5237'],
    acc: '#7dffcf',
    hp: 4,
    lat: 285,
    climb: 0.85,
    thrust: 0.9,
    boostCost: 40,
    radRes: 0.5,
    gravRes: 0.72,
    spd: 2,
    shd: 5,
    ctl: 2,
    bst: 2,
    perk: '4 perisai · radiasi hanya 50% · tarikan gravitasi -28% — lebih lambat & kurang lincah.'
  },
  {
    id: 'phantom',
    name: 'PHANTOM',
    tag: 'Bayangan lincah — kendali ekstrem, boost termurah',
    vr: 3,
    spriteKey: 'phantom',
    hull: ['#f1e6ff', '#b48cff', '#33245e'],
    acc: '#c99aff',
    hp: 3,
    lat: 430,
    climb: 1.0,
    thrust: 1.05,
    boostCost: 25,
    radRes: 1,
    gravRes: 0.9,
    spd: 3,
    shd: 3,
    ctl: 5,
    bst: 5,
    perk: 'Geser paling lincah · boost termurah (25 energi) · sedikit tahan gravitasi.'
  }
];
